---
name: Proc-DaemonLite
version: 0.00_1
author:
  - Nicola Worthington <nicolaw@cpan.org>
abstract: Simple server daemonisation module
license: open_source
requires:
  Carp: 0
  POSIX: 0
recommends:
  Test: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Proc::DaemonLite:
    file: lib/Proc/DaemonLite.pm
    version: 0.00_1
generated_by: Module::Build version 0.2611
