---
name: Proc-DaemonLite
version: 0.02
author:
  - 'Nicola Worthington <nicolaw@cpan.org>'
abstract: Simple server daemonisation module
license: open_source
requires:
  Carp: 0
  Cwd: 0
  File::Basename: 0
  IO::File: 0
  POSIX: 0
  Sys::Syslog: 0
recommends:
  Test: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Proc::DaemonLite:
    file: lib/Proc/DaemonLite.pm
    version: 0.02
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
